title: Lindsey Kvarfordt
description: > # this means to ignore newlines until "baseurl:"
    Portfolio Page for Lindsey Kvarfordt; bachelor in computer science. interest in machine learning and medicine.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Lindsey Kvarfordt # add your name
author-img: lk.jpg # add your photo
about-author: Graduating from Oregon State in Spring 2021.  # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: kvarforl # add your Github handle
social-linkedin: lindsey-kvarfordt # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
